# _config.yml
title: "J_EF: namdeirf.com"   # optional but nice

# IMPORTANT for user sites (namdeirf.github.io)
baseurl: ""                               # keep empty
url: "https://namdeirf.com"               # optional

collections:
  projects:
    output: true
    permalink: /projects/:title/
  brand:
    output: true
    permalink: /brand/:title/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
      category: "uncategorized"
      tags: []
      summary: ""
  - scope:
      path: ""
      type: "brand"
    values:
      layout: brand_item
      published: false         # flip to true per item
      type: "article"          # article | meetup | blog | social | asset
      summary: ""
      impact: []               # list of results/metrics

permalink: pretty
