collections:
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
      category: "uncategorized"
      tags: []
      summary: ""


permalink: pretty
